### ISSUE TITLE
Error clicking NFT button after upgrade to 1.6.1 rc3 [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain-gui#1111]
### What happened?

After an upgrade from 1.6.1 rc2 to rc3, I clicked the NFTs button in the GUI and this error appeared:

```
Something went wrong
Error: (0 , o.useLocalStorage) is not a function
at webpack://@chia/gui/src/hooks/useNFTMetadata.ts:16:60 useNFTsMetadata
at webpack://@chia/gui/src/components/nfts/gallery/NFTGallery.tsx:52:26 NFTGallery
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:267:459 b?b.sibling:null}I
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

My Chia log contains a repetitive error, though it's unclear to me if it is related:
`2022-10-27T10:11:54.127 full_node chia.full_node.mempool  : WARNING  Fee estimator error`

### Version

1.6.1 rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/1112 - should be in RC4 shortly
