### ISSUE TITLE
[BUG] (0 , o.useLocalStorage) is not a function

### ISSUE THREAD

**Issue by shufang79** [Chia-Network/chia-blockchain-gui#1113]
### What happened?

The opening nft page crashed.
![image](https://user-images.githubusercontent.com/51356067/198232150-1508c938-e830-4e47-810a-ca52c9214287.png)

### Version

rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
(0 , o.useLocalStorage) is not a function

URL
#/dashboard/nfts

Stacktrace
at webpack://@chia/gui/src/hooks/useNFTMetadata.ts:16:60 useNFTsMetadata
at webpack://@chia/gui/src/components/nfts/gallery/NFTGallery.tsx:52:26 NFTGallery
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:267:459 b?b.sibling:null}I
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by Ealrann** [comment]
Same here after updating to 6.1 RC3

**Comment by emlowe** [comment]
Thank you a fix is in progress here https://github.com/Chia-Network/chia-blockchain-gui/pull/1112 - should be in an rc4 shortly

**Comment by emlowe** [comment]
Closing as dup of #1111
